[[plugins]]
repo = 'vim-airline/vim-airline'


[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
source ~/.config/nvim/Plugins/vim-airline-themes.vim
'''

[[plugins]]
repo = 'preservim/nerdtree'

[[plugins]]
repo = 'github/copilot.vim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'neoclide/coc.nvim'
source = 'release'
build = 'coc#util#install()'
hook_add = '''
source ~/.config/nvim/Plugins/coc.vim
'''
